### ISSUE TITLE
Laravel 8 compatibility

### ISSUE THREAD

**Issue by fgibaux** [jlorente/laravel-data-migrations#4]
it looks like Laravel 8 broke this package.

at least the MigrateCommand constructor changed and now require a second argument.

is there any plan to support laravel 8?

**Comment by EranNL** [comment]
@fgibaux, It looks like this package is no actively maintained. I made a copy of this project since I was having the same issue as you:
https://github.com/coderan-io/laravel-data-migrations

It works completely the same as this project, but requires >= php 7.4 and of course >= Larave 8.0.

**Comment by fgibaux** [comment]
@emachiels ah great, thank you
