### ISSUE TITLE
Laravel 9 Compatibility

### ISSUE THREAD

**Issue by matthewknill** [jlorente/laravel-data-migrations#6]
Currently get the following when I try and install using composer:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires jlorente/laravel-data-migrations ^2.0 -> satisfiable by jlorente/laravel-data-migrations[2.0.0].
    - jlorente/laravel-data-migrations 2.0.0 requires illuminate/support ^8.0 -> found illuminate/support[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require jlorente/laravel-data-migrations:*" to figure out if any version is installable, or "composer require jlorente/laravel-data-migrations:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by EranNL** [comment]
@matthewknill, It looks like this package is not actively maintained any more. I made a copy of this project since I was having the same issue as you:
https://github.com/coderan-io/laravel-data-migrations

It works completely the same as this project, but requires >= php 7.4 and of course >= Laravel 8.0.

**Comment by matthewknill** [comment]
> @matthewknill, It looks like this package is not actively maintained any more. I made a copy of this project since I was having the same issue as you: https://github.com/coderan-io/laravel-data-migrations
> 
> It works completely the same as this project, but requires >= php 7.4 and of course >= Laravel 8.0.

The last update of this package was 2 years ago whereas the last update of this package was 7 months ago...

**Comment by jlorente** [comment]
Sorry for the delay, I was busy. I have added Laravel 9 support to the package now.
